### ISSUE TITLE
Duplicate versions for mod ID

### ISSUE THREAD

**Issue by ghost** [GamingGuyTyler/fabricarmor#1]
Your Mod ID  collides with the mod  Mineral Collector
 Log: https://paste.ee/p/NBhdM

**Comment by ggtylerr** [comment]
Fixed in the latest commit, will be uploaded to CurseForge as version 1.0.1.

**Comment by ghost** [comment]
Worked! Thank you. :-)

**Comment by ggtylerr** [comment]
No problem.
